In [20]:
import pandas as pd
import numpy as np

df_alters = pd.read_csv('./data/df_alter.csv')

# distance = np.linalg.norm([x - 0.5, y - 0.5])
# apply for rows rather than columns is axis=1
df_alters['distance'] = df_alters.apply(lambda row: np.linalg.norm([row['user_layout_x'] - 0.5, row['user_layout_y'] - 0.5]), axis=1)

# averages of Euclidean distance for every alter
df_concepts_2 = df_alters[["name","distance"]].groupby("name").agg(["count","mean"])
df_concepts_2.columns = ["mentions","distance"]
# Sort the concepts so that least distance is on top.
df_concepts_2.sort_values("distance",ascending=False, inplace=True)
df_concepts_2.head(5)

                 mentions  distance
name
user experience         2  0.284306
art                     1  0.266815
race-ethnicity          2  0.244463
optimisation            6  0.230239
social networks         7  0.227122

In [17]:
# non-averaged Euclidean distance broken down by user
alter_distance_by_user = df_alters.loc[df_alters['name'] == 'race-ethnicity']
alter_distance_by_user[["name", "secret_word", "distance"]]

               name secret_word  distance
29   race-ethnicity   porcupine  0.188387
113  race-ethnicity    helloOII  0.300540

## Claim: 
The merged network uses the average Euclidean distance of an alter from the ego. 

There are only 2 people who put "race-ethnicity" on their sociograms, and because their dstances are far apart and the sample size is small (meaning that *porcupine* placed "race-ethnicity" closer to the center and *helloOII* placed it further) the averaged distance does a poor job of merging these positions.

In [ ]:
unique_secret_words = df_alters['secret_word'].unique()
print(unique_secret_words)

food_secret_words = ['falafel', 'marmite', 'peaches', 'peanuts', 'apples', 'cookie']

food = {}

for i in food_secret_words:
    alter_distance_by_user = df_alters.loc[df_alters['secret_word'] == i]
    smallest_distance = alter_distance_by_user.nsmallest(1, 'distance')
    name = str(smallest_distance["name"].values[0])
    food[i] = name

print(food)